--- !ditz.rubyforge.org,2008-03-06/project 
name: opencraft-acm
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: opencraft-acm
- !ditz.rubyforge.org,2008-03-06/component 
  name: level-builder
- !ditz.rubyforge.org,2008-03-06/component 
  name: physics
- !ditz.rubyforge.org,2008-03-06/component 
  name: security
- !ditz.rubyforge.org,2008-03-06/component 
  name: Commands
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2010-07-02 20:59:43.523878 Z
  log_events: 
  - - 2010-04-25 17:34:56.682355 Z
    - Trever Fischer <tdfischer@fedoraproject.org>
    - created
    - The first OpenCraft Release
  - - 2010-07-02 20:59:43.523911 Z
    - Trever Fischer <tdfischer@fedoraproject.org>
    - released
    - Woo hoo! After a way too long RC period, 0.3 is out the door.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-05-02 19:05:24.044352 Z
    - Trever Fischer <tdfischer@fedoraproject.org>
    - created
    - ""
