--- !ditz.rubyforge.org,2008-03-06/project 
name: opencraft-acm
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: opencraft-acm
- !ditz.rubyforge.org,2008-03-06/component 
  name: level-builder
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-04-25 17:34:56.682355 Z
    - Trever Fischer <tdfischer@fedoraproject.org>
    - created
    - The first OpenCraft Release
